@startuml
actor ユーザ
boundary ブラウザ
control web.php
control kouka1_1Controller
boundary kouka1_1.index.blade.php
boundary layouts.kouka1_1.blade.php
boundary components.menu.blade.php
boundary components.subview.blade.php

ユーザ -> ブラウザ : 該当ページをリクエスト[/kouka1_1]
ブラウザ -> web.php : GET[/kouka1_1]
web.php -> kouka1_1Controller : @index
kouka1_1Controller -> kouka1_1.index.blade.php
kouka1_1.index.blade.php -> layouts.kouka1_1.blade.php : @extends
layouts.kouka1_1.blade.php --> kouka1_1.index.blade.php
kouka1_1.index.blade.php -> components.menu.blade.php : @component
components.menu.blade.php --> kouka1_1.index.blade.php
kouka1_1.index.blade.php -> components.subview.blade.php : @include
components.subview.blade.php --> kouka1_1.index.blade.php
@enduml